[metadata]
app = "torrust-tracker"
purpose = "configuration"
schema_version = "3.0.0"

[logging]
trace_filter = "info"
trace_style = "full"

[core]
listed = false
private = false

[core.database]
driver = "mysql"
host = "mysql"
port = 3306
user = "db_user"
password = "db_user_secret_password"
database = "torrust_tracker"

[udp_tracker_server]
ip_bans_reset_interval_in_secs = 86400
max_connection_id_errors_per_ip = 10
connection_id_validation = "strict"

# Uncomment to enable services

#[[udp_trackers]]
#bind_address = "0.0.0.0:6969"

#[[http_trackers]]
#bind_address = "0.0.0.0:7070"

#[http_api]
#bind_address = "0.0.0.0:1212"

#[http_api.access_tokens]
#admin = "MyAccessToken"
