//! API resources for the [`stats`](crate::v1::context::stats)
//! API context.
use serde::{Deserialize, Serialize};
use torrust_rest_tracker_api_core::statistics::services::{TrackerLabeledMetrics, TrackerMetrics};
use torrust_tracker_metrics::metric_collection::MetricCollection;

/// It contains all the statistics generated by the tracker.
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq)]
pub struct Stats {
    // Torrent metrics
    /// Total number of torrents.
    pub torrents: u64,
    /// Total number of seeders for all torrents.
    pub seeders: u64,
    /// Total number of peers that have ever completed downloading for all torrents.
    pub completed: u64,
    /// Total number of leechers for all torrents.
    pub leechers: u64,

    // Protocol metrics
    /// Total number of TCP (HTTP tracker) connections from IPv4 peers.
    /// Since the HTTP tracker spec does not require a handshake, this metric
    /// increases for every HTTP request.
    pub tcp4_connections_handled: u64,
    /// Total number of TCP (HTTP tracker) `announce` requests from IPv4 peers.
    pub tcp4_announces_handled: u64,
    /// Total number of TCP (HTTP tracker) `scrape` requests from IPv4 peers.
    pub tcp4_scrapes_handled: u64,

    /// Total number of TCP (HTTP tracker) connections from IPv6 peers.
    pub tcp6_connections_handled: u64,
    /// Total number of TCP (HTTP tracker) `announce` requests from IPv6 peers.
    pub tcp6_announces_handled: u64,
    /// Total number of TCP (HTTP tracker) `scrape` requests from IPv6 peers.
    pub tcp6_scrapes_handled: u64,

    // UDP
    /// Total number of UDP (UDP tracker) requests aborted.
    pub udp_requests_aborted: u64,
    /// Total number of UDP (UDP tracker) requests banned.
    pub udp_requests_banned: u64,
    /// Total number of IPs banned for UDP (UDP tracker) requests.
    pub udp_banned_ips_total: u64,
    /// Average rounded time spent processing UDP connect requests.
    pub udp_avg_connect_processing_time_ns: u64,
    /// Average rounded time spent processing UDP announce requests.
    pub udp_avg_announce_processing_time_ns: u64,
    /// Average rounded time spent processing UDP scrape requests.
    pub udp_avg_scrape_processing_time_ns: u64,

    // UDPv4
    /// Total number of UDP (UDP tracker) requests from IPv4 peers.
    pub udp4_requests: u64,
    /// Total number of UDP (UDP tracker) connections from IPv4 peers.
    pub udp4_connections_handled: u64,
    /// Total number of UDP (UDP tracker) `announce` requests from IPv4 peers.
    pub udp4_announces_handled: u64,
    /// Total number of UDP (UDP tracker) `scrape` requests from IPv4 peers.
    pub udp4_scrapes_handled: u64,
    /// Total number of UDP (UDP tracker) responses from IPv4 peers.
    pub udp4_responses: u64,
    /// Total number of UDP (UDP tracker) `scrape` requests from IPv4 peers.
    pub udp4_errors_handled: u64,

    // UDPv6
    /// Total number of UDP (UDP tracker) requests from IPv6 peers.
    pub udp6_requests: u64,
    /// Total number of UDP (UDP tracker) `connection` requests from IPv6 peers.
    pub udp6_connections_handled: u64,
    /// Total number of UDP (UDP tracker) `announce` requests from IPv6 peers.
    pub udp6_announces_handled: u64,
    /// Total number of UDP (UDP tracker) `scrape` requests from IPv6 peers.
    pub udp6_scrapes_handled: u64,
    /// Total number of UDP (UDP tracker) responses from IPv6 peers.
    pub udp6_responses: u64,
    /// Total number of UDP (UDP tracker) `scrape` requests from IPv6 peers.
    pub udp6_errors_handled: u64,
}

impl From<TrackerMetrics> for Stats {
    #[allow(deprecated)]
    fn from(metrics: TrackerMetrics) -> Self {
        Self {
            torrents: metrics.torrents_metrics.total_torrents,
            seeders: metrics.torrents_metrics.total_complete,
            completed: metrics.torrents_metrics.total_downloaded,
            leechers: metrics.torrents_metrics.total_incomplete,
            // TCP
            tcp4_connections_handled: metrics.protocol_metrics.tcp4_connections_handled,
            tcp4_announces_handled: metrics.protocol_metrics.tcp4_announces_handled,
            tcp4_scrapes_handled: metrics.protocol_metrics.tcp4_scrapes_handled,
            tcp6_connections_handled: metrics.protocol_metrics.tcp6_connections_handled,
            tcp6_announces_handled: metrics.protocol_metrics.tcp6_announces_handled,
            tcp6_scrapes_handled: metrics.protocol_metrics.tcp6_scrapes_handled,
            // UDP
            udp_requests_aborted: metrics.protocol_metrics.udp_requests_aborted,
            udp_requests_banned: metrics.protocol_metrics.udp_requests_banned,
            udp_banned_ips_total: metrics.protocol_metrics.udp_banned_ips_total,
            udp_avg_connect_processing_time_ns: metrics.protocol_metrics.udp_avg_connect_processing_time_ns,
            udp_avg_announce_processing_time_ns: metrics.protocol_metrics.udp_avg_announce_processing_time_ns,
            udp_avg_scrape_processing_time_ns: metrics.protocol_metrics.udp_avg_scrape_processing_time_ns,
            // UDPv4
            udp4_requests: metrics.protocol_metrics.udp4_requests,
            udp4_connections_handled: metrics.protocol_metrics.udp4_connections_handled,
            udp4_announces_handled: metrics.protocol_metrics.udp4_announces_handled,
            udp4_scrapes_handled: metrics.protocol_metrics.udp4_scrapes_handled,
            udp4_responses: metrics.protocol_metrics.udp4_responses,
            udp4_errors_handled: metrics.protocol_metrics.udp4_errors_handled,
            // UDPv6
            udp6_requests: metrics.protocol_metrics.udp6_requests,
            udp6_connections_handled: metrics.protocol_metrics.udp6_connections_handled,
            udp6_announces_handled: metrics.protocol_metrics.udp6_announces_handled,
            udp6_scrapes_handled: metrics.protocol_metrics.udp6_scrapes_handled,
            udp6_responses: metrics.protocol_metrics.udp6_responses,
            udp6_errors_handled: metrics.protocol_metrics.udp6_errors_handled,
        }
    }
}

/// It contains all the statistics generated by the tracker.
#[derive(Serialize, Debug, PartialEq)]
pub struct LabeledStats {
    metrics: MetricCollection,
}

impl From<TrackerLabeledMetrics> for LabeledStats {
    #[allow(deprecated)]
    fn from(metrics: TrackerLabeledMetrics) -> Self {
        Self {
            metrics: metrics.metrics,
        }
    }
}

#[cfg(test)]
mod tests {
    use torrust_rest_tracker_api_core::statistics::metrics::{ProtocolMetrics, TorrentsMetrics};
    use torrust_rest_tracker_api_core::statistics::services::TrackerMetrics;

    use super::Stats;

    #[test]
    #[allow(deprecated)]
    fn stats_resource_should_be_converted_from_tracker_metrics() {
        assert_eq!(
            Stats::from(TrackerMetrics {
                torrents_metrics: TorrentsMetrics {
                    total_complete: 1,
                    total_downloaded: 2,
                    total_incomplete: 3,
                    total_torrents: 4
                },
                protocol_metrics: ProtocolMetrics {
                    // TCP
                    tcp4_connections_handled: 5,
                    tcp4_announces_handled: 6,
                    tcp4_scrapes_handled: 7,
                    tcp6_connections_handled: 8,
                    tcp6_announces_handled: 9,
                    tcp6_scrapes_handled: 10,
                    // UDP
                    udp_requests_aborted: 11,
                    udp_requests_banned: 12,
                    udp_banned_ips_total: 13,
                    udp_avg_connect_processing_time_ns: 14,
                    udp_avg_announce_processing_time_ns: 15,
                    udp_avg_scrape_processing_time_ns: 16,
                    // UDPv4
                    udp4_requests: 17,
                    udp4_connections_handled: 18,
                    udp4_announces_handled: 19,
                    udp4_scrapes_handled: 20,
                    udp4_responses: 21,
                    udp4_errors_handled: 22,
                    // UDPv6
                    udp6_requests: 23,
                    udp6_connections_handled: 24,
                    udp6_announces_handled: 25,
                    udp6_scrapes_handled: 26,
                    udp6_responses: 27,
                    udp6_errors_handled: 28
                }
            }),
            Stats {
                torrents: 4,
                seeders: 1,
                completed: 2,
                leechers: 3,
                // TCPv4
                tcp4_connections_handled: 5,
                tcp4_announces_handled: 6,
                tcp4_scrapes_handled: 7,
                // TCPv6
                tcp6_connections_handled: 8,
                tcp6_announces_handled: 9,
                tcp6_scrapes_handled: 10,
                // UDP
                udp_requests_aborted: 11,
                udp_requests_banned: 12,
                udp_banned_ips_total: 13,
                udp_avg_connect_processing_time_ns: 14,
                udp_avg_announce_processing_time_ns: 15,
                udp_avg_scrape_processing_time_ns: 16,
                // UDPv4
                udp4_requests: 17,
                udp4_connections_handled: 18,
                udp4_announces_handled: 19,
                udp4_scrapes_handled: 20,
                udp4_responses: 21,
                udp4_errors_handled: 22,
                // UDPv6
                udp6_requests: 23,
                udp6_connections_handled: 24,
                udp6_announces_handled: 25,
                udp6_scrapes_handled: 26,
                udp6_responses: 27,
                udp6_errors_handled: 28
            }
        );
    }
}
